import "@/styles/globals.css";

import NextAuthProvider from "./(providers)/NextAuthProvider";
import OsuProvider from "./(providers)/OsuProvider";
import { ThemeProvider } from "./(providers)/ThemeProvider";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";

const torus = localFont({
  src: [
    {
      path: "../../public/fonts/TorusRegular.734ed3ae.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/TorusBold.c233ce17.otf",
      weight: "700",
    },
  ],
  variable: "--font-torus",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={`font-sans ${torus.variable}`}>
        <NextAuthProvider>
          <OsuProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextTopLoader showSpinner={false} />
              <Header />
              {children}
            </ThemeProvider>
          </OsuProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
