"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7G1e6JKTvLI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";

import { ModeToggle } from "./mode-toggle";
import { UserProfile } from "./user-profile";
import Image from "next/image";
import { useSession } from "next-auth/react";

export function Header() {
  const session = useSession();

  return (
    <header className="flex items-center justify-between bg-gray-100 px-4 py-3 text-gray-900 dark:bg-gray-900 dark:text-white">
      <div className="flex items-center space-x-4">
        <Link href="/" className="flex items-center space-x-4">
          <Image
            src="/static/osu-logo.svg"
            alt={"osu-l"}
            width={50}
            height={50}
            priority
          />
          <span className="font-bold">osu-chat</span>
        </Link>
      </div>
      <div className="flex items-center space-x-6">
        {session.status === "authenticated" && (
          <>
            <Link className="hover:text-gray-300" href="/browse">
              Browse
            </Link>
            <Link className="hover:text-gray-300" href="/manage-rooms">
              Manage Rooms
            </Link>
          </>
        )}
      </div>
      <div className="flex items-center space-x-4">
        <ModeToggle />
        <UserProfile />
      </div>
    </header>
  );
}
